import fs from 'node:fs';
import path from 'node:path';
import { sha256 } from '../crypto/hash.js';
import { canonicalize } from '../crypto/canonicalize.js';
import { BuildRequest } from './builder.types.js';

export const DEFAULT_ARTIFACTS_DIR =
  path.basename(process.cwd()) === 'server'
    ? path.resolve(process.cwd(), 'data', 'artifacts')
    : path.resolve(process.cwd(), 'server', 'data', 'artifacts');

export interface GeneratedArtifact {
  artifactBytes: Buffer;
  artifactSha256: string;
  artifactSizeBytes: number;
  artifactPath: string;
  buildLog: string;
  buildLogSha256: string;
}

/**
 * Generates a deterministic binary artifact and build log from source inputs.
 * 
 * Guarantees:
 * 1. Identical source inputs (project, version, commit, buildSpec) produce bit-for-bit identical binary bytes.
 * 2. Real SHA-256 hash is computed dynamically from the output bytes.
 * 3. If compromised=true, a malicious byte mutation is injected, altering the SHA-256 while preserving
 *    valid cryptographic signing by the builder.
 */
export function generateDeterministicArtifact(
  request: BuildRequest,
  builderId: string,
  artifactsDir = DEFAULT_ARTIFACTS_DIR
): GeneratedArtifact {
  // Ensure artifacts output directory exists
  if (!fs.existsSync(artifactsDir)) {
    fs.mkdirSync(artifactsDir, { recursive: true });
  }

  // 1. Canonicalize build specification
  const canonicalBuildSpec = canonicalize(request.buildSpec);

  // 2. Compute deterministic seed hash from input parameters
  const seedString = [
    'QUORUM_BUILD_RECIPE_V1',
    request.projectName,
    request.version,
    request.commitSha,
    canonicalBuildSpec,
  ].join('\n');
  const seedHash = sha256(seedString);

  // 3. Assemble binary artifact layout:
  // - Magic Header: 8 bytes (QBIN\x01\x00\x00\x00)
  // - Metadata Section: Commit (40 bytes hex), Project/Version strings
  // - Compiled Code Section: Deterministically generated byte blocks derived from seedHash
  const magic = Buffer.from([0x51, 0x42, 0x49, 0x4e, 0x01, 0x00, 0x00, 0x00]); // "QBIN\x01\x00\x00\x00"
  const commitBuf = Buffer.from(request.commitSha.padEnd(40, '0').slice(0, 40), 'utf8');
  
  // Deterministic body generated by repeating seed hash bytes to simulate compiled executable
  const bodyBlocks: Buffer[] = [];
  for (let i = 0; i < 8; i++) {
    const blockDigest = sha256(`${seedHash}:block:${i}`);
    bodyBlocks.push(Buffer.from(blockDigest, 'hex'));
  }
  let artifactBytes = Buffer.concat([magic, commitBuf, ...bodyBlocks]);

  // 4. Handle Compromised / Divergence Injection:
  // If builder is compromised, inject malicious modification (e.g. trojan backdoor signature)
  if (request.compromised) {
    const backdoorPayload = Buffer.from('\xde\xad\xbe\xef\x00\x01_INJECTED_BACKDOOR_PAYLOAD_X99_', 'utf8');
    artifactBytes = Buffer.concat([artifactBytes, backdoorPayload]);
  } else if (request.divergenceVariant) {
    const variantPayload = Buffer.from(`_DIVERGENCE_VARIANT_${request.divergenceVariant}_`, 'utf8');
    artifactBytes = Buffer.concat([artifactBytes, variantPayload]);
  }

  // 5. Calculate REAL SHA-256 digest of the actual artifact bytes
  const artifactSha256 = sha256(artifactBytes);
  const artifactSizeBytes = artifactBytes.length;

  // 6. Write artifact to local disk
  const filename = `${builderId}-${request.expectedArtifactName}`;
  const artifactPath = path.join(artifactsDir, filename);
  fs.writeFileSync(artifactPath, artifactBytes);

  // 7. Generate deterministic build log
  const logLines = [
    '================================================================',
    `QUORUM REPRODUCIBLE BUILD LOG - BUILDER: ${builderId}`,
    '================================================================',
    `Project:          ${request.projectName}`,
    `Version:          ${request.version}`,
    `Repository:       ${request.repoUrl}`,
    `Source Commit:    ${request.commitSha}`,
    `Build Spec:       ${canonicalBuildSpec}`,
    `Artifact Name:    ${request.expectedArtifactName}`,
    `Artifact Size:    ${artifactSizeBytes} bytes`,
    `Artifact SHA-256: ${artifactSha256}`,
    `Status:           ${request.compromised ? 'BACKDOOR_INJECTED_SIMULATION' : 'SUCCESS_CLEAN_BUILD'}`,
    '================================================================',
  ];
  const buildLog = logLines.join('\n');
  const buildLogSha256 = sha256(buildLog);

  return {
    artifactBytes,
    artifactSha256,
    artifactSizeBytes,
    artifactPath,
    buildLog,
    buildLogSha256,
  };
}
